name: Release
on:
  push:
    branches:
      - temp
jobs:
  pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Check For PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: ${{ env.GITHUB_BASE_REF }}
        run: |
          BRANCH=${GITHUB_REF##*/}
          echo "Check If PR exists for $BRANCH"
          gh pr list -R "$GITHUB_REPOSITORY" --base "$BRANCH" --state open --label "Release $BRANCH"
          if [[ "$(gh pr list -R "$GITHUB_REPOSITORY" --base "$BRANCH" --state open --label "Release $BRANCH")" == "" ]]; then
            echo "Creating PR"
            gh pr create -R "$GITHUB_REPOSITORY" --base beta --label "Release $BRANCH" --title "Release $BRANCH"
          fi