name: Release
on:
  push:
    branches:
      - temp
jobs:
  pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Check For PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: ${{ env.GITHUB_BASE_REF }}
        run: |
          echo "Check If PR exists for $GITHUB_BASE_REF"
          gh pr list --base "$GITHUB_BASE_REF" --state open --label "Release $GITHUB_BASE_REF"
          if [[ "$(gh pr list --base "$GITHUB_BASE_REF" --state open --label "Release $GITHUB_BASE_REF")" == "" ]]; then
            echo "Creating PR"
          fi