name: "build-test"
on: 
  schedule:
    - cron: '*/5 * * * *'
  pull_request:

jobs:
  lint: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with: 
        reportIgnoredFiles: true